/*
 *
 * NAF Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"free5gc/src/app"
	"free5gc/src/naf/logger"
	"free5gc/src/naf/service"
	"free5gc/src/naf/version"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"
)

var NAF = &service.NAF{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "naf"
	fmt.Print(app.Name, "\n")
	appLog.Infoln("NAF version: ", version.GetVersion())
	app.Usage = "-free5gccfg common configuration file -nafcfg naf configuration file"
	app.Action = action
	app.Flags = NAF.GetCliCmd()

	err := app.Run(os.Args)
	if err != nil {
		panic(err)
	}
}

func action(c *cli.Context) {
	app.AppInitializeWillInitialize(c.String("free5gccfg"))
	NAF.Initialize(c)
	NAF.Start()
}
